### ISSUE TITLE
request bond not available in Emulator?!

### ISSUE THREAD

**Issue by jpbusman** [sam-dumont/GarminGoProDatafield#10]
I cannot get it working with Nordic usb and emulator, on real device it works

Error: Symbol Not Found Error
Details: Could not find symbol 'requestBond'
Stack: 
  - onConnectedStateChanged() at C:\Users\janp\OneDrive\Garmin\GoproDatafield\GarminGoProDatafield\source\GoPro.mc:430 0x1000181b

**Comment by sam-dumont** [comment]
This is a limitation in Garmin Connect SDK, nothing that can be done about it right now. I hope they will fix it because it makes development much more complex as no debugging can be done currently.
